GET http://localhost:8000/sync/chat?query=한국의 수도는?
###
GET http://localhost:8000/async/chat?query=한국의 수도는?
###
GET http://localhost:8000/streaming_sync/chat?query=한국의 수도는?
###
GET http://localhost:8000/streaming_async/chat?query=한국의 수도는?
###
GET http://localhost:8000/openai